version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: mi_postgres_container
    restart: always
    environment:
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_password_seguro
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - unlocku-red

  pgadmin:
    image: dpage/pgadmin4
    container_name: mi_pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@correo.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8088:80"
    depends_on:
      - postgres_db
    networks:
      - unlocku-red

  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: mi_app_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: 
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
      SESSION_SECRET: "una_frase_larga_y_random_cualquiera"
      FRONTEND_URL: https://unlock-u.vercel.app
      BACKEND_URL: http://back-cefai.fi.uncoma.edu.ar
      BACKEND_CALLBACK: http://back-cefai.fi.uncoma.edu.ar
    depends_on:
      - postgres_db
    volumes:
      - ./back:/app
      - /app/node_modules
    networks:
      - unlocku-red

  vite-app:
    container_name: front_unlocku
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Podrás acceder desde tu navegador en http://localhost:8080
    restart: always
    environment: 
      VITE_BACKEND_URL: http://back-cefai.fi.uncoma.edu.ar

networks:
  unlocku-red:
    driver: bridge

volumes:
  postgres_data:
